Repository tvkitchen/countertop, pull requests merged in 2020-07, with the labels that each got.

#72 Delete .github, community health files
  .github/ISSUE_TEMPLATE/discussion.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/task.md
  .github/pull_request_template.md
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
Labels: documentation

#79 Rename /src/lib to /src/tools
  README.md
  lib/utils/jest.setup.js
  src/components/ingestion/AbstractIngestionEngine.js
  src/components/ingestion/__test__/AbstractIngestionEngine.unit.test.js
  src/index.js
  src/tools/kafka/index.js
  src/tools/logger/index.js
  src/tools/utils/__test__/data/loadTestData.json
  src/tools/utils/__test__/index.unit.test.js
  src/tools/utils/__test__/jest.unit.test.js
  src/tools/utils/__test__/mpegts.unit.test.js
  src/tools/utils/index.js
  src/tools/utils/jest.js
  src/tools/utils/mpegts.js
Labels: SHAME

#75 Create HTTP ingestion engine
  package.json
  src/components/ingestion/HttpIngestionEngine.js
  src/components/ingestion/__test__/HttpIngestionEngine.unit.test.js
  yarn.lock
Labels: enhancement
